const Sounds = {
    "thoiDaiDoDa.mp3": require("../../assets/sound/ThoiKy/thoiDaiDoDa.mp3"),
    "thoiDaiDoDongDa.mp3": require("../../assets/sound/ThoiKy/thoiDaiDoDongDa.mp3"),
    "thoiDaiDoSat.mp3": require("../../assets/sound/ThoiKy/thoiDaiDoSat.mp3"),
    "xichQuy.mp3": require("../../assets/sound/ThoiKy/xichQuy.mp3"),
    "vanLang.mp3": require("../../assets/sound/ThoiKy/vanLang.mp3"),
    "nhaThuc.mp3": require("../../assets/sound/ThoiKy/nhaThuc.mp3"),
    "bacThuoc1.mp3": require("../../assets/sound/ThoiKy/bacThuoc1.mp3"),
    "haiBaTrung.mp3": require("../../assets/sound/ThoiKy/haiBaTrung.mp3"),
    "bacThuoc2.mp3": require("../../assets/sound/ThoiKy/bacThuoc2.mp3"),
    "tienLy.mp3": require("../../assets/sound/ThoiKy/tienLy.mp3"),
    "bacThuoc3.mp3": require("../../assets/sound/ThoiKy/bacThuoc3.mp3"),
    "kyTuChu.mp3": require("../../assets/sound/ThoiKy/kyTuChu.mp3"),
    "thoiKyDocLap.mp3": require("../../assets/sound/ThoiKy/thoiKyDocLap.mp3"),
    "bacThuoc4.mp3": require("../../assets/sound/ThoiKy/bacThuoc4.mp3"),
    "thoiKyTrungHung.mp3": require("../../assets/sound/ThoiKy/thoiKyTrungHung.mp3"),
    "thoiKyChiaHet.mp3": require("../../assets/sound/ThoiKy/thoiKyChiaHet.mp3"),
    "thoiKyThongNhat.mp3": require("../../assets/sound/ThoiKy/thoiKyThongNhat.mp3"),
    "thoiKyPhapThuoc.mp3": require("../../assets/sound/ThoiKy/thoiKyPhapThuoc.mp3"),
    "thoiKyNhatThuoc.mp3": require("../../assets/sound/ThoiKy/thoiKyNhatThuoc.mp3"),
    "khangChienChongPhap.mp3": require("../../assets/sound/ThoiKy/khangChienChongPhap.mp3"),
    "chienTranhChongMy.mp3": require("../../assets/sound/ThoiKy/chienTranhChongMy.mp3"),
    "thoiKyDauSauThongNhat.mp3": require("../../assets/sound/ThoiKy/thoiKyDauSauThongNhat.mp3"),
    "thoiKyDoiMoi.mp3": require("../../assets/sound/ThoiKy/thoiKyDoiMoi.mp3"),

    "trieuDaiNgo.mp3": require("../../assets/sound/TrieuDai/trieuDaiNgo.mp3"),
    "trieuDinh.mp3": require("../../assets/sound/TrieuDai/trieuDinh.mp3"),
    "trieuDaiTienLe.mp3": require("../../assets/sound/TrieuDai/trieuDaiTienLe.mp3"),
    "trieuLy.mp3": require("../../assets/sound/TrieuDai/trieuLy.mp3"),
    "trieuDaiNhaTran.mp3": require("../../assets/sound/TrieuDai/trieuDaiNhaTran.mp3"),
    "trieuDaiNhaHo.mp3": require("../../assets/sound/TrieuDai/trieuDaiNhaHo.mp3"),
    "trieuDaiLeSo.mp3": require("../../assets/sound/TrieuDai/trieuDaiLeSo.mp3"),
    "trieuDaiNhaMac.mp3": require("../../assets/sound/TrieuDai/trieuDaiNhaMac.mp3"),
    "trieuDaiTaySon.mp3": require("../../assets/sound/TrieuDai/trieuDaiTaySon.mp3"),
    "trieuNguyen.mp3": require("../../assets/sound/TrieuDai/trieuNguyen.mp3"),
};

export default Sounds;
